### PR TITLE
Fixed error in event service description and added buggy remote contr…

### PR DESCRIPTION
**Pull request by bluetooth-mdw**

### CODE REVIEW

**Comment by jamesadevine** [comment]
@bluetooth-mdw Thanks Martin! Will merge later on today along!

**Comment by jamesadevine** [comment]
@bluetooth-mdw Just reviewed this...

Instead of using `<pre>` HTML tags, could you replace this with the markup using for code?

```markdown
```cpp
```

(And the closing markdown back ticks)

**Comment by jamesadevine** [comment]
You can see an example of the markdown code tags here: https://raw.githubusercontent.com/lancaster-university/microbit-docs/master/docs/ubit.md

**Comment by bluetooth-mdw** [comment]
Roger that. WIll do.

**Comment by jamesadevine** [comment]
Thanks @bluetooth-mdw - live.

**Pull request merged**
