### PR TITLE
UART example: Return from onConnect() when disconnected

### PR DESCRIPTION
**Pull request by stigbjorlykke**
Update the UART example to return from onConnect() when disconnected
to allow multiple connect/disconnects.

### CODE REVIEW

**Comment by jamesadevine** [comment]
@stigbjorlykke Looks like a good patch :smile:

I will test and merge locally.

**Comment by bluetooth-mdw** [comment]
Totally agree. Good catch from @stigbjorlykke :-)

**Comment by jamesadevine** [comment]
Deployed :smile:

**Comment by bluetooth-mdw** [comment]
I'm updating the associated code now....

**Comment by jamesadevine** [comment]
Thanks @bluetooth-mdw, great stuff!

**Pull request merged**
