### PR TITLE
 uBit.bleManager.advertiseEddystoneUrl: URL length

### PR DESCRIPTION
**Pull request by OwenBrotherwood**
a proposed explanation of the URL length without listing all the byte encoding possible.

### CODE REVIEW

**Comment by OwenBrotherwood** [comment]
Oops :)

**Comment by OwenBrotherwood** [comment]
Or rather Oops, corrected

**Comment by OwenBrotherwood** [comment]
update of text with focus on the URL prefix and the the remaining characters 
```
where the https:// is encoded as one byte and is placed in the URL prefix and the remaining 14 characters are placed in the available space of 17
```

**Comment by OwenBrotherwood** [comment]
Can this PR be merged?
Downstream repository is waiting for this PR in order to finish a PR on their doc.

**Comment by OwenBrotherwood** [comment]
Apologies Lancaster. 
Although the text supplied is ok, I have not created a correct formatting of the presentation at  https://lancaster-university.github.io/microbit-docs/ble/eddystone/#starting-advertising
I seem to have missed the possibility of paragraphs to break the text up into correct paragraphs.

I can create another PR if Lancaster wishes a correction or feel free to change the formatting (and of course any text at Lancaster's discretion).

**Comment by jamesadevine** [comment]
Sure, i thought it looked ok!

**Comment by OwenBrotherwood** [comment]
OK: I am happy if Lancaster is happy.
Thanks James

**Pull request merged**
