### PR TITLE
Updated wrt new Magnetometer Calibration characteristic and support f…

### PR DESCRIPTION
**Pull request by smartyw**
…or Write Without Response by the Client Event characteristic

### CODE REVIEW

**Comment by microbit-sam** [comment]
@smartyw
The calibration characteristic isn't documented at the moment, I've had a quick scan of this PR and it looks like it's still relevant - do you think so too?

If so this should be merged to master!

**Comment by smartyw** [comment]
I had no idea it had not been merged. Yes, it's relevant. I can document if you like. No point until it's merged and released though.

**Comment by microbit-sam** [comment]
Ok cool!
@jamesadevine @finneyj could you merge this when you get a chance please 😄

**Comment by microbit-sam** [comment]
Thanks @jamesadevine !

**Pull request merged**
